from . import law_case
from . import res_partner
from . import hr_employee
from . import law_case_stage
from . import law_case_milestone
from . import law_case_evidence
from . import law_case_witness
from . import law_legal_topic
from . import law_case_precedent
from . import legal_area